// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gflyrjxifhcvdyhrqgee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmbHlyanhpZmhjdmR5aHJxZ2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzM4MDksImV4cCI6MjA3MjY0OTgwOX0.0u_4mYF9Q4WUULM-l9anUuT6vraXIJ_iI_86307xujM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});